### ISSUE TITLE
All items are shown in select default page form regardless the registry setting to filter items with a given content-type

### ISSUE THREAD

**Issue by erral** [plone/plone.app.content#182]
There is a registry setting to filter the items available to be selected as default page according to their content-type.

Anyway the code here adds them to the list:

https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/selection.py#L128

If all checks fail, the item is added to the result list.

I will try to write a test and a fix.

**Comment by mauritsvanrees** [comment]
I have lost track of what is okay to merge and what should still be tested together. Several Jenkins jobs have passed, others have errors that may not matter. Let's test everything together.

Let's see, we want this on Plone 5.1 and 5.2, right?

On 5.1:

```
https://github.com/plone/plone.app.content/pull/185
https://github.com/plone/Products.CMFPlone/pull/2954
https://github.com/plone/plone.app.upgrade/pull/217
```

On 5.2:

```
https://github.com/plone/plone.app.content/pull/184
https://github.com/plone/Products.CMFPlone/pull/2955
https://github.com/plone/plone.app.upgrade/pull/217
```

I have rebased a few of these branches, to get in the latest changes. That may avoid some failures on Jenkins. I will start jobs for these two combinations.

**Comment by mauritsvanrees** [comment]
I have [fixed a naming mismatch](https://github.com/plone/plone.app.upgrade/pull/217/commits/bdecbe23bf97c44e6b40b07e49182dd82fc567e3) in the plone.app.upgrade PR. That should hopefully fix the test failures.

**Comment by mauritsvanrees** [comment]
All Plone 5.2 jobs pass successfully! 
Plone 5.1 has [one robot error](https://jenkins.plone.org/job/pull-request-5.1/150/robot/Robot/Test%20Edit/Scenario%3A%20Form%20dropdowns%20follows%20DateTime%20widget%20values/), but that seems a temporary error: "No browser is open.".

This seems good. I will merge.
They would be best merged together, and then get Jenkins to run at the end, but we cannot enforce that. So some jobs may temporarily fail until everything is merged. I will do the CMFPlone merges first, then plone.app.content, then plone.app.upgrade. I think that gives the least chance of temporary test failures.

**Comment by mauritsvanrees** [comment]
I have merged all. Thanks @erral!

**Comment by erral** [comment]
Thank you @mauritsvanrees for taking care of these. I was busy this last week and couldn't pay attention to it.
