### ISSUE TITLE
Check pyupgrade changes.

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.content#214]
I made changes with `pyupgrade` and accidentally pushed to master instead of to a PR branch. Sorry!

Can someone review the changes? Master branch is for Plone 6 only. Tests of the package pass locally with Python 3.8.

The big commit is 380204d8d98d9e60802c4722f11f8303a7af6751.
And two small follow-up commits where I do minor cleanup: 0851fd6f503b55c0f14c65c97c587e3946bae324 and 84c699df891d0fc2c94daddb1d427ade5682b74c.

**Comment by jensens** [comment]
No problem, LGTM. Thanks!

**Comment by ale-rt** [comment]
LGTM to me too :)
