### ISSUE TITLE
Test fails with Products.CMFCore 3.1 (explicit acquisition)

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.content#264]
See also https://github.com/plone/buildout.coredev/pull/865#issuecomment-1590765809, where I initially updated coredev 6.0 to use new `Products.CMFCore` 3.1, but needed to revert it.

The good thing is that only one test in Plone fails.  It fails on [this line](https://github.com/plone/plone.app.content/blob/4.0.1/plone/app/content/tests/test_actions.py#L146).  This is a test to check that you cannot accidentally delete an item through acquisition.  this is a test for [this issue](https://github.com/plone/Products.CMFPlone/issues/383), fixed for Plone 5.0 in https://github.com/plone/plone.app.content/pull/28.

The failing test comes from that PR.  It is actually *good* that it fails now.  It sets up this scenario:

- an item `test` in the root
- a folder `f1` also with in item `test`
- In two separate browsers open `f1/test/delete_confirmation`.
- In both browsers click to delete.

What happens until now: the `delete_confirmation` browser view checks if the to-be-deleted item is the intended item or if it is implicitly acquired from somewhere else.  In the last case it shows a warning: "item has already been deleted".

With `CMFCore` 3.1, the click in the second browser gives a 404 NotFound.  This is good.

I think we **must** keep the current check in `delete_confirmation` for safety.  But the test should be fixed to work with both versions of CMFCore.  I will create a PR

cc @jaroel

**Comment by jaroel** [comment]
This should address that https://github.com/plone/plone.app.content/pull/263

**Comment by mauritsvanrees** [comment]
Ah, @jaroel already handled this with PR #263. :-)  I will merge that one.

**Comment by mauritsvanrees** [comment]
Just saw the PR before I saw your comment. :-)
