### ISSUE TITLE
DefaultPageSelectionView deliver empty result in get_selectable_items

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.content#290]
the catalog query need an absolute physical path, it's introduced by https://github.com/plone/plone.app.content/commit/0b08a9b3b3192b717a8370901e19102df95e140d

now:

`path={"query": context.absolute_url_path(), "depth": 1},`

but it should be:

`path={"query": '/'.join(context.getPhysicalPath()), "depth": 1},`

`context.absolute_url_path()` doesn't return the full physical path in a vhm environment.

@jensens what was the intention by this change? i would like to revert the change if you confirm.

**Comment by petschki** [comment]
better twice then never 😉 

https://github.com/plone/Products.CMFPlone/issues/4001
https://github.com/plone/plone.app.content/pull/292

**Comment by petschki** [comment]
fixed in #292

**Comment by davisagli** [comment]
Sorry, I thought these two are equivalent, but I guess I was mistaken. Thanks for the fix.
