### ISSUE TITLE
Uploading a txt-file tries to create a Document instead of a File and fails

### ISSUE THREAD

**Issue by pbauer** [plone/plone.app.content#33]
This happens in 5.0b2 and master-branch. Here is the traceback: 

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module Products.PDBDebugMode.runcall, line 70, in pdb_runcall
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.app.content.browser.file, line 147, in __call__
    UnboundLocalError: local variable 'size' referenced before assignment

**Comment by fgrcon** [comment]
plone 5.04b / virgin plone site created --> upload +.txt, or *.py ...

/plone/app/content/browser/file.py ` __call__()`:

     # Determine if the default file/image types are DX or AT based
     ctr = getToolByName(self.context, 'content_type_registry')
     type_ = ctr.findTypeName(filename.lower(), '', '') or 'File'      <-------

Products/CMFCore/ContentTypeRegistry.py
    
    findTypeName( self, name, typ, body ):
        """
            Perform a lookup over a collection of rules, returning the
            the name of the Type object corresponding to name/typ/body.
            Return None if no match found.
        """
        .....

I get: 

     content_type_registry.predicates:
    {
    'xml': (<MajorMinorPredicate at xml>, 'File'), 
    'ATNewsItem_ext': (<ExtensionPredicate at ATNewsItem_ext>, 'News Item'),
    'sha1': (<ExtensionPredicate at sha1>, 'File'),
    'text': (<MajorMinorPredicate at text>, 'Document'),
    'ATEvent_ext': (<ExtensionPredicate at ATEvent_ext>, 'Event'),
    'ATImage_ext': (<ExtensionPredicate at ATImage_ext>, 'Image'),
    'application_xhtml+xml': (<MajorMinorPredicate at application_xhtml+xml>, 'Document'),
    'application': (<MajorMinorPredicate at application>, 'File'),
    'video': (<MajorMinorPredicate at video>, 'File'),
    'ATDocument_ext': (<ExtensionPredicate at ATDocument_ext>, 'Document'),
    'message_rfc822': (<MajorMinorPredicate at message_rfc822>, 'Document'),
    'tsv': (<MajorMinorPredicate at tsv>, 'File'),
    'ATLink_ext': (<ExtensionPredicate at ATLink_ext>, 'Link'),
    'csv': (<MajorMinorPredicate at csv>, 'File'),
    'image': (<MajorMinorPredicate at image>, 'Image'),
    'css': (<MajorMinorPredicate at css>, 'File'),
    'audio': (<MajorMinorPredicate at audio>, 'File')}

and:

    content_type_registry.predicates['ATDocument_ext'][0].extensions
    ['txt', 'stx', 'rst', 'rest', 'py']

For these extensions type Document is returned and leads to failure
**I am somewhat confused:**  I thought, I got  rid of Archetypes ?
**How to proceed?**
btw: There are arguments typ and body I don't understand nor found any doc about ... ?
