### ISSUE TITLE
Folder content view adds Uploads to wrong folder

### ISSUE THREAD

**Issue by hgarus** [plone/plone.app.content#35]
In plone 5.0b2 when I open the folder contents in one folder say `/a` then navigate to a different folder say `/a/b` and upload a File using the upload button, the file gets added to `/a` instead of `/a/b/`.

I have tracked this issue down to plone/mockup@27471487b5a71 which made the structure pattern expect `portal_type` instead of `Type` inside `fc-contextInfo`. I will add a pull request which adds `portal_type` to the attributes of the `fc-contextInfo` view.

**Comment by jensens** [comment]
fixed by ba23cdc71eb18ab891eacaf76735b5a9b205ee47, thanks for PR and report anyway
