### ISSUE TITLE
Pressing "Cancel" on delete_confirmation on the context of an image is broken

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.app.content#38]
The handle_cancel method:
 - https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/actions.py#L74
redirects to the context absolute_url, which in the context of an image returns the image stream:

![image](https://cloud.githubusercontent.com/assets/1300763/8779993/997e4f18-2f06-11e5-9660-41bd64ff44a9.png)

I think we should change this to the default view.

**Comment by vangheem** [comment]
absolute_url should never return an image stream. Something else is happening.

**Comment by vangheem** [comment]
What version of plone 5 are you testing on? I can not reproduce on master.

**Comment by ale-rt** [comment]
I am using Plone-5.0b2.

> absolute_url should never return an image stream. Something else is happening.

Maybe some addon is changing the Image base view.

Will check this on master.

**Comment by ale-rt** [comment]
I tried with buildout coredev and effectively I am not able to reproduce it anymore.

Perhaps someone introduced some javascript magic that fixed the popup.

Anyway I think this is still an issue. 

If you go here:
 - http://localhost:8080/Plone/your-image-url/delete_confirmation
and click cancel you see the issue.
Delete confirmation redirects you here:
 - http://localhost:8080/Plone/your-image-url
instead of the more reasonable default view:
 - http://localhost:8080/Plone/your-image-url/view

Will try to provide a patch as soon as possible.

**Comment by ale-rt** [comment]
The situation is weird :)

With this patch:
```diff
diff --git a/plone/app/content/browser/actions.py b/plone/app/content/browser/actions.py
index cb95120..4a1e99d 100644
--- a/plone/app/content/browser/actions.py
+++ b/plone/app/content/browser/actions.py
@@ -40,6 +40,15 @@ class DeleteConfirmationForm(form.Form, LockingBase):
     template = ViewPageTemplateFile('templates/delete_confirmation.pt')
     enableCSRFProtection = True
 
+    def view_url(self):
+        ''' Facade to the homonymous plone_context_state method
+        '''
+        context_state = getMultiAdapter(
+            (self.context, self.request),
+            name='plone_context_state'
+        )
+        return context_state.view_url()
+
     @property
     def items_to_delete(self):
         catalog = getToolByName(self.context, 'portal_catalog')
@@ -72,7 +81,7 @@ class DeleteConfirmationForm(form.Form, LockingBase):
     @button.buttonAndHandler(
         _(u'label_cancel', default=u'Cancel'), name='Cancel')
     def handle_cancel(self, action):
-        self.request.response.redirect(self.context.absolute_url())
+        self.request.response.redirect(self.view_url())
 
 
 def valid_id(self):
```
the flow visting this url (the javascript-less behaviour):
 - http://localhost:8080/Plone/your-image-url/delete_confirmation

is fixed.

**But** the popup breaks in an awkward way... 

What happens is that the form (posted with an ajax call), get's the view (instead of the image) and then it goes to the image view...

![image](https://cloud.githubusercontent.com/assets/1300763/8825348/b06c73d4-307e-11e5-838c-2384509ea427.png)

**Comment by vangheem** [comment]
Yes, the modal should just be changed to close the modal if cancel is clicked.

**Comment by vangheem** [comment]
Wait, re-reading your comment, don't you want the image view? That's the correct behavior.

**Comment by ale-rt** [comment]
Thanks @vangheem for taking care :)

> Wait, re-reading your comment, don't you want the image view? That's the correct behavior.

I do want the delete_confirmation to return a redirect to the view_url (e.g. http://localhost:8080/Plone/a.jpg/view) and not the absolute_url (e.g. http://localhost:8080/Plone/a.jpg).
IMHO this should be the correct behaviour of that form.

With my patch it is working perfectly if you traverse to the form, e.g. going to http://localhost:8080/Plone/a.jpg/delete_confirmation and clicking cancel redirects you to http://localhost:8080/Plone/a.jpg/view.

But there is a problem when you use that view with pat-modal. 
This call:
```
window.parent.location.href = options.redirectToUrl.apply(self, [$action, response, options]);
```
set's the next target to the data-base-url read in the html, see:
 - https://github.com/plone/mockup/blob/88f6bc586be3e8d531aa88f1242f1cb24e27eddc/mockup/patterns/modal/pattern.js#L163

Which for an image turns out to be the raw image.

Of course this method returns an empty baseUrl if the delete_confirmation returns the image (actual behaviour of master).

Note: as a side effect of this behaviour, images can weigh several MBs...

**Comment by vangheem** [comment]
Ahh, that's your patch. Can you create a PR?

**Comment by ale-rt** [comment]
Yes, but I will add a check: if the request is an ajax one I will return a small string (empty? a json?), if it is not I will return the view_url.

**Comment by ale-rt** [comment]
Maybe it is also possible to make some modifications here:
 - https://github.com/plone/Products.CMFPlone/blob/5bd4f60cfb3fda656b20653954a592bb0a8b9294/Products/CMFPlone/profiles/default/actions.xml#L192

but looking to pat-plone-modal options it does not seem possible to fix this behaviour.

**Comment by vangheem** [comment]
Mixing plain html forms with ajax modal forms is really hard and should be avoided if possible.

**Comment by ale-rt** [comment]
I agree, I wanted to avoid this.
Do you see any other way to solve this issue?

Submitted the PR, I ran succesfully the tests on this package, but still waiting for ./bin/alltest

**Comment by vangheem** [comment]
Don't worry about runing ./bin/alltest locally. Just running the jenkins job for the PR: http://jenkins.plone.org/job/pull-request-5.0/118/

**Comment by ale-rt** [comment]
Thanks a lot for your support.
Anyway I would think to a better solution :/
The issue is wide spread, for example the object_rename form is affected by the same problem.

My main concern is that we are making an ajax request that potentially downloads an high quality image.

I think that fixing this has implications on plone-pat-modal.

**Comment by vangheem** [comment]
Fixing this correctly could be:

1) re-implement forms with javascript instead of trying to make non-ajax forms work like this
2) try to make plone-pat-modal handle MORE cases and do this better. It's already insane what it tries to do because this problem is hard...
3) disable modals

If you can find a decent solution, that'd be great. I think plone 5.1 needs a plip to replace pat-plone-modal with a new implementation that is only mean to work with ajax and then we actually implement all the forms we want correctly.

**Comment by pbauer** [comment]
The issue is still there for files and images (in coredev). Steps to repoduce:
- Create Image
- Click Actions > Delete
- Click Cancel
The redirect to ``/view`` only happens when not using a modal. With a modal nothing happens.

**Comment by ale-rt** [comment]
This is really bad!

There is an issue with pat-modal redirects. I am trying to fix that issue with this pull:
 - https://github.com/plone/plone.app.layout/pull/55
In addition I am removing the double behavior on the delete_confirmation form, see:
 - https://github.com/plone/plone.app.content/pull/49

Anyway there is a more general issue (#42),
After we find a valid solution for the delete action (and a valid solution, IMHO, means that if you click cancel the modal just disappears with no call to the server) we should apply it also to the other actions (e.g. rename).

**Comment by vangheem** [comment]
I think the real fix here is to use the "disableAjaxFormSubmit":true option on the modal options in portal_actions config

**Comment by vangheem** [comment]
Also see: https://github.com/plone/mockup/commit/413a1bdc71feaf1c1231d30fa3187fbcec865865

**Comment by ale-rt** [comment]
On Tue, Aug 11, 2015 at 3:04 PM, Nathan Van Gheem <notifications@github.com>
wrote:

> Also see: plone/mockup@413a1bd
> <https://github.com/plone/mockup/commit/413a1bdc71feaf1c1231d30fa3187fbcec865865>
>
>
I was playing with option in the ZMI, but I was never able to have a proper
behavior for both the "Delete" and "Cancel" buttons.
Maybe you have more experience than me and with five minutes of ZMI can fix
this.
-- 
Alessandro Pisa - RedTurtle Technology
E-mail: alessandro.pisa@redturtle.it
Web Site: http://www.redturtle.it
Phone: +39 0532 1915958

**Comment by vangheem** [comment]
I screwed up and didn't mean to put this on master but this is the correct modal option fix: https://github.com/plone/Products.CMFPlone/commit/e57a314dba4b662cebda8f4528cacb25c1d7f721

formsUseAjax is not even a valid option.

Could you test with development mode active on the bundles? If we're good, I can build and commit the production resources.

**Comment by ale-rt** [comment]
Sure

**Comment by ale-rt** [comment]
I think e57a314 should be reverted: it fixes the cancel action, but not the delete one.

In http://localhost:8080/Plone/portal_actions/object_buttons/delete/manage_propertiesForm I see:
![image](https://cloud.githubusercontent.com/assets/1300763/9199371/522733b2-4042-11e5-886a-7f043a58c6cb.png)

With this setting if I click cancel it redirects me to http://localhost:8080/Plone/plone.png/view which is no longer there.

As said in my previous comment I was playing with several options in the ZMI but was never able to have a proper behavior for both actions.

Anyway if we revert e57a314 we are anyway quite close to the solution after:
 - https://github.com/plone/plone.app.layout/pull/55
 - https://github.com/plone/mockup/pull/551
it should be enough to rebuild the bundles, am I wrong?

**Comment by vangheem** [comment]
huh, it's working properly for me.

> With this setting if I click cancel it redirects me to http://localhost:8080/Plone/plone.png/view which is no longer there.
Are you saying that it deletes it when you click cancel?

**Comment by ale-rt** [comment]
If I click cancel it deletes the image and the redirects to the image view, but of course I get a 404.
I made the test with a fresh checkout and a brand new plone site.

**Comment by vangheem** [comment]
And with development mode enabled for the bundles?

**Comment by vangheem** [comment]
This is my behavior: https://www.dropbox.com/s/6thcbf68x6s1rja/toolbar-example.mov?dl=0

**Comment by ale-rt** [comment]
This is my:
 - https://www.youtube.com/watch?v=aCloTVZmSl4&feature=youtu.be

**Comment by vangheem** [comment]
And you're in development mode for the bundles "plone" and "plone-logged-in"?

**Comment by ale-rt** [comment]
yes :)
![image](https://cloud.githubusercontent.com/assets/1300763/9200629/07de573e-4049-11e5-86e3-dd738f4013e1.png)

**Comment by ale-rt** [comment]
Thiis is what is happening:
![image](https://cloud.githubusercontent.com/assets/1300763/9201213/1e5900ba-404c-11e5-87f6-2592cc744096.png)

After getting a respinse from delete confirmation we want to go to the root of the Plone site, but later we are submitted to the view of the image (which has been deleted)

**Comment by vangheem** [comment]
I understand. I can't reproduce what you are seeing though.

**Comment by ale-rt** [comment]
Ok, I will try to refresh my development environment.
Anyway thanks for your kind help!

**Comment by ale-rt** [comment]
Cannot reproduce this issue with a recent checkout
