### ISSUE TITLE
Fix test isolation problems

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.content#73]
http://jenkins.plone.org/job/pull-request-5.0/940 reports that there are some tests that do commits in an integration test. That's a serious test isolation problem.

See https://github.com/plone/plone.testing/issues/19

**Comment by gforcada** [comment]
Either fixed or I was wrong...

**Comment by gforcada** [comment]
I was wrong, there are test isolation problems: see http://jenkins.plone.org/job/pull-request-5.0/1010/console

**Comment by thet** [comment]
Fixed with: https://github.com/plone/plone.app.content/pull/84
