### ISSUE TITLE
plone.app.content circular dependency old Zope DateTime

### ISSUE THREAD

**Issue by 1letter** [plone/plone.app.content#89]
I got an error when i use the folder_listing view of a folder. The Folder contain many Events. This Site was a migrated Instance from an old Plone 4.0.1 Version with AT to Plone 5.0.4 with DX.
I debugged it and find the solution for me. i don't know if this is generally usefull. Here my code:

``` python
# -*- coding: utf-8 -*-
# utils.py
import Missing
import datetime
import json
import DateTime

def custom_json_handler(obj):
    if obj == Missing.Value:
        return None
    if type(obj) == DateTime.DateTime:
        return obj.asdatetime().isoformat()
    if type(obj) in (datetime.datetime, datetime.date):
        return obj.isoformat()
    return obj


def json_dumps(data):
    return json.dumps(data, default=custom_json_handler)


# can eventually provide custom handling here if we want
json_loads = json.loads
```

**Comment by witekdev** [comment]
@1letter I used your code and factored in another scenario (sets) and created a pull request:
https://github.com/plone/plone.app.content/pull/92

**Comment by neilferreira** [comment]
I believe this should have been fixed by @pcdummy in https://github.com/plone/plone.app.content/commit/b87e937da9616183415b094df84f35114fa0be1f

I'm still running into this issue, even when running 3.3.2

**Comment by gforcada** [comment]
Seems to be fixed, co closing, re-open if needed.
