### ISSUE TITLE
Master branch versus 3.1.x

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.app.content#98]
In coredev 5.0, @gforcada has set the plone.app.content branch to 3.1.x at the end of May: https://github.com/plone/buildout.coredev/commit/f99797224716e872e1d23bf570447fe6df9cf6d8

But the master branch has had a few commit since then and is at version 3.1.3.dev0 after @esteele released version 3.1.2 a few days ago.

I do see that Gil had updated the version to 3.2 initially: https://github.com/plone/plone.app.content/commit/ff8d1a6dcc97fc1c158e9ec7933e9f3cd3834a39
And that I have downgraded it: https://github.com/plone/plone.app.content/commit/d5df82d27cc022a593d94c2fe5460b7380c082ef

Plone 5.0.4 has plone.app.content 3.0.20
Plone 5.0.5 has plone.app.content 3.1.1.

Is coredev 5.0 maybe meant to use branch 3.0.x instead of 3.1.x? All seems well in combination with 3.1.x. Version 3.1(.0) does have some new features, so maybe it was meant not to go in Plone 5.0. But it has already happened by now.

So: a bit of a strange mess. Maybe this also partly explains why in https://github.com/plone/plone.app.content/pull/97 Jenkins wants me to also test on 5.1 even though the branch I want to merge to is 3.1.x.

CC @thet since he made the most changes recently.

**Proposal**:

- Let coredev 5.0 use the master branch again.
- Remove the 3.1.x branch.

**Comment by gforcada** [comment]
I think that was in preparation for merging the c.indexing PLIP.
El dia 08/07/2016 19:37, "Maurits van Rees" <notifications@github.com> va
escriure:

**Comment by thet** [comment]
@mauritsvanrees the changes in plone.app.content 3.1.x are necessary for the changes in the structure pattern of mockup 2.3.0, which is still not released (and still can wait a bit IMO - I'm currently preparing another patch of changes which could go into this release). CMFPlone ships with mockup 2.1.x. So, CMFPlone 5.0 should use plone.app.content 3.0.x.

**Comment by mauritsvanrees** [comment]
@thet Well, Plone 5.0.5 is already using plone.app.content 3.1.1... Is anything expected to go wrong in combination with mockup 2.1.x?

**Comment by mauritsvanrees** [comment]
As I proposed earlier, I have let coredev 5.0 use the master branch again, and have removed the 3.1.x branch.
When the collective.indexing branch is merged, we might need to bump the version and recreate a maintenance 3.1.x branch.
